### PR TITLE
Serializer compression per new message

### PR DESCRIPTION
**Pull request by bobbyrenwick**
@EDITD/hackers, this allows users of `queue_util` to specify the `serializer` and `compression` for every new message that the `handle_data` function returns

### CODE REVIEW

**Comment by Fizzadar** [comment]
LGTM

**Comment by pkatseas** [comment]
Left a couple notes but love where this is going! :+1:

**Comment by bobbyrenwick** [comment]
Thanks for the reviews @Fizzadar, @sujaymansingh, @Fizzadar we all missed out the most important part of these changes: actually passing the `serializer` and `compression` to the `get_queue` call!

Please could you have a look at my latest commits and let me know what you think?

**Comment by Fizzadar** [comment]
Changes LGTM @bobbyrenwick!

**Comment by pkatseas** [comment]
Changes LGTMT

**Comment by bobbyrenwick** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;d5FIcvBx&#x2F;21-deal-with-rebrews"> Deal with Rebrews</a>

**Comment by bobbyrenwick** [comment]
Thanks for the reviews all!

**Pull request merged**
