### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by bobbyrenwick**
@EDITD/hackers, this converts `queue_util` to a python3 package.

### CODE REVIEW

**Comment by Fizzadar** [comment]
LGTM! Does it work in py2?

**Comment by johnspicer** [comment]
LGTM

**Comment by pkatseas** [comment]
LGTM!

**Comment by sujaymansingh** [comment]
LGTM!

**Comment by bobbyrenwick** [comment]
Thanks for the reviews!

**Pull request merged**
